CREATE TYPE [dbo].[TY_MonthlyRent] AS TABLE (
	IDNO				VARCHAR(10) NOT NULL,
	WorkDayHours		FLOAT NOT NULL,
	HolidayHours		FLOAT NOT NULL,
	MotorTotalHours		FLOAT NOT NULL,
	StartDate			DATETIME NOT NULL,
	EndDate				DATETIME NOT NULL,
	SEQNO				INT NOT NULL,
	ProjID				VARCHAR(20) NOT NULL,
	ProjNM				NVARCHAR(50) NOT NULL
);
GO