/****** Object:  Table [dbo].[IRENT_SIGNATURE]    Script Date: 2021/1/21 下午 04:16:33 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[IRENT_SIGNATURE](
	[A_PRGID] [varchar](10) NOT NULL,
	[A_USERID] [varchar](10) NOT NULL,
	[A_SYSDT] [datetime] NULL,
	[U_PRGID] [varchar](10) NOT NULL,
	[U_USERID] [varchar](10) NOT NULL,
	[U_SYSDT] [datetime] NULL,
	[MEMIDNO] [varchar](20) NOT NULL,
	[SIGNATURE] [varchar](8000) NOT NULL,
 CONSTRAINT [PK_IRENT_SIGNATURE] PRIMARY KEY CLUSTERED 
(
	[MEMIDNO] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[IRENT_SIGNATURE] ADD  CONSTRAINT [DF_IRENT_SIGNATURE_MEMIDNO]  DEFAULT ('') FOR [MEMIDNO]
GO

ALTER TABLE [dbo].[IRENT_SIGNATURE] ADD  CONSTRAINT [DF_IRENT_SIGNATURE_SIGNATURE]  DEFAULT ('') FOR [SIGNATURE]
GO

