CREATE TABLE [dbo].[MEMBER_NEW] (
    [A_PRGID]       VARCHAR (10)    CONSTRAINT [DF_MEMBER_NEW_A_PRGID] DEFAULT ('') NULL,
    [A_USERID]      VARCHAR (10)    CONSTRAINT [DF_MEMBER_NEW_A_USERID] DEFAULT ('') NULL,
    [A_SYSDT]       DATETIME        CONSTRAINT [DF_MEMBER_NEW_A_SYSDT] DEFAULT (getdate()) NULL,
    [U_PRGID]       VARCHAR (10)    CONSTRAINT [DF_MEMBER_NEW_U_PRGID] DEFAULT ('') NULL,
    [U_USERID]      VARCHAR (10)    CONSTRAINT [DF_MEMBER_NEW_U_USERID] DEFAULT ('') NULL,
    [U_SYSDT]       DATETIME        CONSTRAINT [DF_MEMBER_NEW_U_SYSDT] DEFAULT (getdate()) NULL,
    [MEMRFNBR]      INT             IDENTITY (1, 1) NOT NULL,
    [MEMCNAME]      NVARCHAR (50)   CONSTRAINT [DF_MEMBER_NEW_MEMCNAME] DEFAULT ('') NULL,
    [MEMIDNO]       VARCHAR (10)    CONSTRAINT [DF_MEMBER_NEW_MEMIDNO] DEFAULT ('') NULL,
    [MEMPWD]        VARCHAR (100)   CONSTRAINT [DF_MEMBER_NEW_MEMPWD] DEFAULT ('') NULL,
    [MEMSEX]        CHAR (1)        CONSTRAINT [DF_MEMBER_NEW_MEMSEX] DEFAULT ('') NULL,
    [MEMBIRTH]      DATETIME        CONSTRAINT [DF_MEMBER_NEW_MEMBIRTH] DEFAULT ('') NULL,
    [MEMMARRY]      CHAR (1)        CONSTRAINT [DF_MEMBER_NEW_MEMMARRY] DEFAULT ('') NULL,
    [MEMTEL_ZIP]    VARCHAR (5)     CONSTRAINT [DF_MEMBER_NEW_MEMTEL_ZIP] DEFAULT ('') NULL,
    [MEMTEL]        VARCHAR (20)    CONSTRAINT [DF_MEMBER_NEW_MEMTEL] DEFAULT ('') NULL,
    [MEMTEL_EXT]    VARCHAR (10)    CONSTRAINT [DF_MEMBER_NEW_MEMTEL_EXT] DEFAULT ('') NULL,
    [MEMCEIL]       VARCHAR (20)    CONSTRAINT [DF_MEMBER_NEW_MEMCEIL] DEFAULT ('') NULL,
    [MEMCITY]       INT             CONSTRAINT [DF_MEMBER_NEW_MEMCITY] DEFAULT ((0)) NULL,
    [MEMCOUNTRY]    INT             CONSTRAINT [DF_MEMBER_NEW_MEMCOUNTRY] DEFAULT ((0)) NULL,
    [MEMADDR]       NVARCHAR (200)  CONSTRAINT [DF_MEMBER_NEW_MEMADDR] DEFAULT ('') NULL,
    [MEMEMAIL]      VARCHAR (100)   CONSTRAINT [DF_MEMBER_NEW_MEMEMAIL] DEFAULT ('') NULL,
    [MEMSELKEY_I]   INT             CONSTRAINT [DF_MEMBER_NEW_MEMSELKEY_I] DEFAULT ((0)) NULL,
    [MEMSELKEY_J]   INT             CONSTRAINT [DF_MEMBER_NEW_MEMSELKEY_J] DEFAULT ((0)) NULL,
    [MEMCOMPANY]    VARCHAR (40)    CONSTRAINT [DF_MEMBER_NEW_MEMCOMPANY] DEFAULT ('') NULL,
    [MEMCOMTEL_ZIP] VARCHAR (5)     CONSTRAINT [DF_MEMBER_NEW_MEMCOMTEL_ZIP] DEFAULT ('') NULL,
    [MEMCOMTEL]     VARCHAR (20)    CONSTRAINT [DF_MEMBER_NEW_MEMCOMTEL] DEFAULT ('') NULL,
    [MEMCOMTEL_EXT] VARCHAR (10)    CONSTRAINT [DF_MEMBER_NEW_MEMCOMTEL_EXT] DEFAULT ('') NULL,
    [MEMCOMCITY]    INT             CONSTRAINT [DF_MEMBER_NEW_MEMCOMCITY] DEFAULT ((0)) NULL,
    [MEMCOMCOUNTRY] INT             CONSTRAINT [DF_MEMBER_NEW_MEMCOMCOUNTRY] DEFAULT ((0)) NULL,
    [MEMCOMADDR]    NVARCHAR (200)  CONSTRAINT [DF_MEMBER_NEW_MEMCOMADDR] DEFAULT ('') NULL,
    [MEMCOMNONEED]  CHAR (1)        CONSTRAINT [DF_MEMBER_NEW_MEMCOMNONEED] DEFAULT ('') NULL,
    [MEMCOMTITLE]   VARCHAR (40)    CONSTRAINT [DF_MEMBER_NEW_MEMCOMTITLE] DEFAULT ('') NULL,
    [MEMCOMNO]      VARCHAR (10)    CONSTRAINT [DF_MEMBER_NEW_MEMCOMNO] DEFAULT ('') NULL,
    [MEMCONTRACT]   NVARCHAR (50)   CONSTRAINT [DF_MEMBER_NEW_MEMCONTRACT] DEFAULT ('') NULL,
    [MEMSELKEY_K]   INT             CONSTRAINT [DF_MEMBER_NEW_MEMSELKEY_K] DEFAULT ((0)) NULL,
    [MEMCONTEL_ZIP] VARCHAR (5)     CONSTRAINT [DF_MEMBER_NEW_MEMCONTEL_ZIP] DEFAULT ('') NULL,
    [MEMCONTEL]     VARCHAR (20)    CONSTRAINT [DF_MEMBER_NEW_MEMCONTEL] DEFAULT ('') NULL,
    [MEMCONTEL_EXT] VARCHAR (10)    CONSTRAINT [DF_MEMBER_NEW_MEMCONTEL_EXT] DEFAULT ('') NULL,
    [MEMEPAPER]     CHAR (1)        CONSTRAINT [DF_MEMBER_NEW_MEMEPAPER] DEFAULT ('') NULL,
    [MEMEBONUS]     FLOAT (53)      CONSTRAINT [DF_MEMBER_NEW_MEMEBONUS] DEFAULT ((5)) NULL,
    [MEMAPPLYDATE]  DATETIME        CONSTRAINT [DF_MEMBER_NEW_MEMAPPLYDATE] DEFAULT (getdate()) NULL,
    [MEMGROUP]      CHAR (1)        CONSTRAINT [DF_MEMBER_NEW_MEMGROUP] DEFAULT ('') NULL,
    [MEMLNGCOUNT]   INT             CONSTRAINT [DF_MEMBER_NEW_MEMLNGCOUNT] DEFAULT ((0)) NULL,
    [MEMLNGDATE]    DATETIME        CONSTRAINT [DF_MEMBER_NEW_MEMLNGDATE] DEFAULT ('') NULL,
    [MEMMEMO]       NVARCHAR (1000) CONSTRAINT [DF_MEMBER_NEW_MEMMEMO] DEFAULT ('') NULL,
    [MEMMEMO_1]     VARCHAR (5000)  CONSTRAINT [DF_MEMBER_NEW_MEMMEMO_1] DEFAULT ('') NULL,
    [MEMSTARFNBR]   INT             CONSTRAINT [DF_MEMBER_NEW_MEMSTARFNBR] DEFAULT ((0)) NULL,
    [MEMSTAFF]      CHAR (2)        CONSTRAINT [DF_MEMBER_NEW_MEMSTAFF] DEFAULT ('') NULL,
    [MEMTAG]        CHAR (1)        CONSTRAINT [DF_MEMBER_NEW_MEMTAG] DEFAULT ('N') NULL,
    [MEMCOUNT_P]    INT             CONSTRAINT [DF_MEMBER_NEW_MEMCOUNT_P] DEFAULT ((0)) NULL,
    [MEMCOUNT_S]    INT             CONSTRAINT [DF_MEMBER_NEW_MEMCOUNT_S] DEFAULT ((0)) NULL,
    [STADT]         DATETIME        CONSTRAINT [DF_MEMBER_NEW_STADT] DEFAULT (CONVERT([datetime],CONVERT([varchar],getdate(),(111)),(0))) NULL,
    [ENDDT]         DATETIME        CONSTRAINT [DF_MEMBER_NEW_ENDDT] DEFAULT (CONVERT([datetime],'2099/12/31',(0))) NULL,
    [FAMILY]        INT             CONSTRAINT [DF_MEMBER_NEW_FAMILY] DEFAULT ((0)) NULL,
    [INCOMEY]       INT             CONSTRAINT [DF_MEMBER_NEW_IMCOMEY] DEFAULT ('1') NULL,
    [RENTFOR]       INT             CONSTRAINT [DF_MEMBER_NEW_RENTFOR] DEFAULT ('1') NULL,
    [SYSCD]         VARCHAR (6)     CONSTRAINT [DF_MEMBER_NEW_SYSCD] DEFAULT ('ER') NOT NULL,
    [MEMMSG]        VARCHAR (1)     CONSTRAINT [DF_MEMBER_NEW_MEMMSG] DEFAULT ('Y') NOT NULL,
    [MEMMSGMEMO]    NVARCHAR (200)  CONSTRAINT [DF_MEMBER_NEW_MEMMSGMEMO] DEFAULT ('') NOT NULL,
    [MEMCD]         CHAR (1)        NULL,
    [MEMPOST2]      VARCHAR (10)    NULL,
    [MEMCITY2]      VARCHAR (10)    NULL,
    [MEMCOUNTRY2]   VARCHAR (10)    NULL,
    [MEMADDR2]      NVARCHAR (100)  NULL,
    [MEMVERCD]      CHAR (1)        NULL,
    [WEBFLG]        VARCHAR (1)     NULL,
    [EVFLG]         VARCHAR (1)     NULL,
    [IRENTFLG]      VARCHAR (1)     CONSTRAINT [DF_MEMBER_NEW_IRENTFLG] DEFAULT ('') NOT NULL,
    [DRIVERNO]      VARCHAR (20)    CONSTRAINT [DF_MEMBER_NEW_DRIVERNO] DEFAULT ('') NOT NULL,
    [SIDENTITY]     VARCHAR (5)     CONSTRAINT [DF_MEMBER_NEW_SIDENTITY] DEFAULT ('') NULL,
    [CARDCD]        VARCHAR (5)     CONSTRAINT [DF_MEMBER_NEW_CARDCD] DEFAULT ('') NOT NULL,
    [CARDRECVCD]    VARCHAR (5)     CONSTRAINT [DF_MEMBER_NEW_CARDRECVCD] DEFAULT ('') NOT NULL,
    [CARDNO1]       VARCHAR (30)    CONSTRAINT [DF_MEMBER_NEW_CARDNO1] DEFAULT ('') NOT NULL,
    [CARDNO2]       VARCHAR (30)    CONSTRAINT [DF_MEMBER_NEW_CARDNO2] DEFAULT ('') NOT NULL,
    [CARDRECVDT]    DATETIME        NULL,
    [CARDSENDDT]    DATETIME        NULL,
    [ADDCD]         VARCHAR (5)     CONSTRAINT [DF_MEMBER_NEW_ADDCD] DEFAULT ('') NOT NULL,
    [APISTATUS]     VARCHAR (2)     CONSTRAINT [DF_MEMBER_NEW_APISTATUS] DEFAULT ('') NOT NULL,
    [APISTATUS2]    VARCHAR (5)     CONSTRAINT [DF_MEMBER_NEW_APISTATUS2] DEFAULT ('') NOT NULL,
    [IRENTSTATUS]   VARCHAR (5)     CONSTRAINT [DF_MEMBER_NEW_IRENTSTATUS] DEFAULT ('') NOT NULL,
    [IRENTSENDCD]   VARCHAR (5)     NULL,
    [IRENTBRNHCD]   VARCHAR (10)    NULL,
    [BOOKLETSENDDT] DATETIME        CONSTRAINT [DF_MEMBER_NEW_BOOKLETSENDDT] DEFAULT ('') NULL,
    [SIDENTITYSDT]  DATETIME        CONSTRAINT [DF_MEMBER_NEW_SIDENTITYSDT] DEFAULT ('') NULL,
    [SIDENTITYEDT]  DATETIME        CONSTRAINT [DF_MEMBER_NEW_SIDENTITYEDT] DEFAULT ('') NULL,
    [HTCID]         VARCHAR (150)   CONSTRAINT [DF__MEMBER_NE__HTCID__16E43C86] DEFAULT ('') NOT NULL,
    [HTTIME]        DATETIME        NULL,
    [QUICKFLG]      VARCHAR (1)     CONSTRAINT [DF_MEMBER_NEW_QUICKFLG] DEFAULT ('') NOT NULL,
    [MARKETING]     VARCHAR (1)     NULL,
    [MEMLICENCE01]  VARCHAR (1)     CONSTRAINT [DF__MEMBER_NE__MEMLI__2F3C7FB2] DEFAULT ('N') NOT NULL,
    [MEMLICENCE02]  VARCHAR (1)     CONSTRAINT [DF__MEMBER_NE__MEMLI__3030A3EB] DEFAULT ('N') NOT NULL,
    [MEMLICENCE03]  VARCHAR (1)     CONSTRAINT [DF__MEMBER_NE__MEMLI__3124C824] DEFAULT ('N') NOT NULL,
    [MEMLICENCE04]  VARCHAR (1)     CONSTRAINT [DF__MEMBER_NE__MEMLI__3218EC5D] DEFAULT ('N') NOT NULL,
    [PW_ENCODE_VER] VARCHAR (20)    NULL,
    CONSTRAINT [PK_MEMBER_NEW] PRIMARY KEY CLUSTERED ([MEMRFNBR] ASC) WITH (FILLFACTOR = 90)
);




GO



GO



GO



GO



GO



GO



GO
CREATE NONCLUSTERED INDEX [IDX_MEMIDNO]
    ON [dbo].[MEMBER_NEW]([MEMIDNO] ASC) WITH (FILLFACTOR = 90);

