CREATE TABLE [dbo].[MEMBER_NEW_ONTRANS] (
    [A_PRGID]        VARCHAR (10)  NOT NULL,
    [A_USERID]       VARCHAR (10)  NOT NULL,
    [A_SYSDT]        DATETIME      NOT NULL,
    [U_PRGID]        VARCHAR (10)  NOT NULL,
    [U_USERID]       VARCHAR (10)  NOT NULL,
    [U_SYSDT]        DATETIME      NOT NULL,
    [MEMIDNO]        VARCHAR (10)  NOT NULL,
    [INVPVDCD]       VARCHAR (1)   CONSTRAINT [DF__MEMBER_NE__INVPV__10422BEF] DEFAULT ('') NOT NULL,
    [CARRIERID]      VARCHAR (50)  CONSTRAINT [DF__MEMBER_NE__CARRI__11365028] DEFAULT ('') NOT NULL,
    [MEMRIGDATE]     DATETIME      NULL,
    [NPOBAN]         VARCHAR (50)  CONSTRAINT [DF__MEMBER_NE__NPOBA__122A7461] DEFAULT ('') NOT NULL,
    [RTNACC_FLG]     VARCHAR (1)   CONSTRAINT [DF__MEMBER_NE__RTNAC__4D41E3E5] DEFAULT ('') NOT NULL,
    [RTNACC_TOKEN]   VARCHAR (100) CONSTRAINT [DF__MEMBER_NE__RTNAC__4E36081E] DEFAULT ('') NOT NULL,
    [LEGALAGENT_FLG] VARCHAR (1)   CONSTRAINT [DF__MEMBER_NE__LEGAL__71352B98] DEFAULT ('N') NOT NULL,
    [INVBOXTYPE]     VARCHAR (2)   NULL,
    [IDTYPE]         VARCHAR (10)  NULL
);


GO
CREATE NONCLUSTERED INDEX [IX_MEMBER_NEW_ONTRANS]
    ON [dbo].[MEMBER_NEW_ONTRANS]([MEMIDNO] ASC) WITH (STATISTICS_NORECOMPUTE = ON);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'法定代理人已審核', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'MEMBER_NEW_ONTRANS', @level2type = N'COLUMN', @level2name = N'LEGALAGENT_FLG';

