CREATE TABLE [dbo].[TB_OrderModifyLog]
(
	[modifyId]                      INT  IDENTITY (1, 1) NOT NULL,
	 [order_number]                 INT            NOT NULL,
    [already_lend_car]             TINYINT        DEFAULT ((0)) NOT NULL,
    [already_return_car]           TINYINT        DEFAULT ((0)) NOT NULL,
    [extend_stop_time]             DATETIME       NULL,
    [force_extend_stop_time]       DATETIME       NULL,
    [final_start_time]             DATETIME       NULL,
    [final_stop_time]              DATETIME       NULL,
    [start_door_time]              DATETIME       NULL,
    [end_door_time]                DATETIME       NULL,
    [transaction_no]               NVARCHAR (100) DEFAULT ('') NOT NULL,
    [final_price]                  INT            DEFAULT ((0)) NOT NULL,
    [pure_price]                   INT            DEFAULT ((0)) NOT NULL,
    [mileage_price]                INT            DEFAULT ((0)) NOT NULL,
    [fine_price]                   INT            DEFAULT ((0)) NOT NULL,
    [fine_interval]                INT            DEFAULT ((0)) NOT NULL,
    [fine_rate]                    INT            DEFAULT ((0)) NOT NULL,
    [gift_point]                   INT            DEFAULT ((0)) NOT NULL,
    [Etag]                         INT            DEFAULT ((0)) NOT NULL,
    [already_payment]              INT            DEFAULT ((0)) NOT NULL,
    [start_mile]                   FLOAT          DEFAULT ((0)) NOT NULL,
    [end_mile]                     FLOAT          DEFAULT ((0)) NOT NULL,
    [trade_status]                 INT            DEFAULT ((0)) NOT NULL,
    [payment_status_from_front]    TINYINT        DEFAULT ((0)) NOT NULL,
    [payment_status_from_platform] TINYINT        DEFAULT ((0)) NOT NULL,
    [U_PRGID]                      NVARCHAR (50)  NULL,
    [U_USERID]                     NVARCHAR (50)  NULL,
    [U_SYSDT]                      DATETIME       NULL,
    [U_Reson]                      INT            NULL,
    [U_Remark]                     NVARCHAR (50)  NULL, 
    CONSTRAINT [PK_TB_OrderModifyLog] PRIMARY KEY CLUSTERED ([modifyId] ASC)
)
