CREATE TABLE [dbo].[TB_OrderModifyLog]
(
	[modifyId]                      INT  IDENTITY (1, 1) NOT NULL,
	[order_number] [int] NOT NULL,
	[already_lend_car] [tinyint] NOT NULL DEFAULT 0,
	[already_return_car] [tinyint] NOT NULL DEFAULT 0,
	[extend_stop_time] [datetime] NULL,
	[force_extend_stop_time] [datetime] NULL,
	[final_start_time] [datetime] NULL,
	[final_stop_time] [datetime] NULL,
	[start_door_time] [datetime] NULL,
	[end_door_time] [datetime] NULL,
	[transaction_no] [nvarchar](500) NOT NULL DEFAULT N'',
	[final_price] [int] NOT NULL DEFAULT 0,
	[pure_price] [int] NOT NULL DEFAULT 0,
	[mileage_price] [int] NOT NULL DEFAULT 0,
	[Insurance_price][int] NOT NULL DEFAULT 0,
	[fine_price] [int] NOT NULL DEFAULT 0,
	[fine_interval] [int] NOT NULL DEFAULT 0,
	[fine_rate] [int] NOT NULL DEFAULT 0,
	[gift_point] [int] NOT NULL DEFAULT 0,
    [gift_motor_point] [int] NOT NULL DEFAULT 0,
    [monthly_workday] [float] not null DEFAULT 0.0,
    [monthly_holiday] [float] not null DEFAULT 0.0,
	[Etag] [int] NOT NULL DEFAULT 0,
	[already_payment] [int] NOT NULL DEFAULT 0,
	[start_mile] [float] NOT NULL DEFAULT 0,
	[end_mile] [float] NOT NULL DEFAULT 0,
	[trade_status] [int] NOT NULL DEFAULT 0,
	[parkingFee] [int] NOT NULL DEFAULT 0, 
    [parkingSpace] NVARCHAR(128) NOT NULL DEFAULT N'', 
    [TransDiscount] INT NOT NULL DEFAULT -1, 
    [U_PRGID]                      NVARCHAR (50)  NULL,
    [U_USERID]                     NVARCHAR (50)  NULL,
    [U_SYSDT]                      DATETIME       NULL,
    [U_Reson]                      INT            NULL,
    [U_Remark]                     NVARCHAR (50)  NULL, 
    CONSTRAINT [PK_TB_OrderModifyLog] PRIMARY KEY CLUSTERED ([modifyId] ASC)
)
