base_path: "C:\\others\\book"
category: "Investment"
# second
sleep: 0.5
is_test: false

book:
    name: "ALL_2023_06"
    start_at: 2
    total_pages: 84

location:
    left_top: []
    right_bottom: []
