base_path: "C:\\others\\book"
category: "english"
# second
sleep: 0.5
is_test: true

book:
    name: "ALL_2023_06"
    start_at: 2
    total_pages: 84

location:
    left_top: [-2160, 520]
    right_bottom: [-3, 3432]
