from pynput import keyboard

# Flag to indicate if the key event is generated by the script itself
ignore_event = False

def on_press(key):
    global ignore_event
    if ignore_event:
        return

    try:
        if key == keyboard.Key.space:
            ignore_event = True
            keyboard_controller.press(keyboard.Key.down)
            keyboard_controller.release(keyboard.Key.down)
        elif key == keyboard.Key.down:
            ignore_event = True
            keyboard_controller.press(keyboard.Key.space)
            keyboard_controller.release(keyboard.Key.space)
        else:
            keyboard_controller.press(key)
            keyboard_controller.release(key)
    except AttributeError:
        pass
    finally:
        ignore_event = False

def on_release(key):
    global ignore_event
    if ignore_event:
        return

    try:
        if key == keyboard.Key.space:
            ignore_event = True
            keyboard_controller.release(keyboard.Key.down)
        elif key == keyboard.Key.down:
            ignore_event = True
            keyboard_controller.release(keyboard.Key.space)
        else:
            keyboard_controller.release(key)
    except AttributeError:
        pass
    finally:
        ignore_event = False

keyboard_controller = keyboard.Controller()

with keyboard.Listener(on_press=on_press, on_release=on_release) as listener:
    listener.join()
