is_test: true
path:
    download: "C:\\Users\\sean2\\Downloads"
    destination: "C:\\others\\anime_download"

filter:
    # MB
    size: 50
    min_created_before: 60
    file_type: [".mp4"]

anime:
    name: "The Eminence in Shadow"
    position:
        # press english dub button
        dub: [1487, 1814]
        # play button
        # play: [799 , 1487]wq
        # next episode button
        next: [2206, 1590]
        # anime web position
        # tab: []
    episode:
        count: 12
        # section of retain
        sections: [
                # 1
                [["1:00", "2:00"], ["4:00", "5:00"]],
                # # 2
                [["1:00", "2:00"]],
                # # 3
                # [["0:00", "10:00"]],
            ]

download_tool:
    wait:
        # wait for anime play (sec)
        play: 10
        # wait for video loading (sec)
        loading: 180
    position:
        icon: [3312, 97]
        open_download_page: [2788, 164]
        # tab: []
        # download after video loading
        download: [2487, 954]
