is_test: false
path:
    download: "C:\\Users\\sean2\\Downloads"
    destination: "C:\\others\\anime_download"

filter:
    # MB
    size: 50
    min_created_before: 60
    file_type: ['.mp4']

anime:
    name: 'My Happy Marriage'
    position:
        # press english dub button
        dub: [925, 1016]
        # play button
        play: [436, 822]
        # next episode button
        next: [1292, 871]
        # anime web position
        # tab: []
    episode:
        count: 12
        # section of retain
        sections: [
                # 1
                [],
                # 2
                [],
                # 3
                [],
                # 4
                [],
                # 5
                [],
                # 6
                [],
                # 7
                [],
                # 8
                [],
                # 9
                [],
                # 10
                [],
                # 11
                [],
                # 12
                [],
            ]

download_tool:
    wait:
        # wait for anime play (sec)
        play: 10
        # wait for video loading (sec)
        loading: 180
    position:
        icon: [1601, 83]
        open_download_page: [1268, 123]
        # tab: []
        # download after video loading
        download: [1320, 655]
