isTest: true
path:
    download: ""
    destination: ""

filter:
    # MB
    size: 50
    min_created_before: 60
    file_type: [".mp4"]

anime:
    name: ""
    position:
        # press english dub button
        dub: []
        # play button
        play: []
        # next episode button
        next: []
        # anime web position
        tab: []
    episode:
        count: 12
        # section of retain
        section: []

download_tool:
    wait:
        # wait for anime play (sec)
        play: 10
        # wait for video loading (sec)
        loading: 120
    position:
        icon: []
        open_download_page: []
        # tab: []
        # download after video loading
        download: []
