is_test: true
path:
    download: "C:\\Users\\sean2\\Downloads"
    destination: "C:\\others\\anime_download"

filter:
    # MB
    size: 50
    min_created_before: 60
    file_type: [".mp4"]

anime:
    name: "My Happy Marriage"
    position:
        # press english dub button
        dub: [-2320, 1846]
        # play button
        play: [-3038, 1538]
        # next episode button
        next: [-1679, 1635]
        # anime web position
        # tab: []
    episode:
        count: 2
        # section of retain
        sections: [
                # 1
                [["0:00", "24:47"]],
                # # # 2
                [["0:00", "0:50"], ["2:21": "22:20"]],
                # # # 3
                # [["0:00", "10:00"]],
            ]

download_tool:
    wait:
        # wait for anime play (sec)
        play: 10
        # wait for video loading (sec)
        loading: 180
    position:
        icon: [-517, 136]
        open_download_page: [-1024, 209]
        # tab: []
        # download after video loading
        download: [-1374, 1003]
