version: '3.2'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: unless-stopped
    ports:
      - "1434:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=r^JJo032+A0^
      - TZ=Europe/Berlin
      - MSSQL_PID=Express
    volumes:
      - "./data:/var/opt/mssql/data/"
      - "./log:/var/opt/mssql/log/"
      - "./secrets:/var/opt/mssql/secrets/"