BEGIN

	BEGIN TRAN
	DECLARE @MEMBER_IRENT_DISTINCT TABLE (
	A_SYSDT DATETIME,
	MEMRFNBR INT
	)
	INSERT INTO @MEMBER_IRENT_DISTINCT(MEMRFNBR,A_SYSDT)
	SELECT MEMRFNBR,MAX(A_SYSDT) 
	FROM MEMBER_IRENT WITH(NOLOCK) 
	WHERE AUDITCD='01' GROUP BY MEMRFNBR


	DECLARE @MEMBER_IRENT TABLE (
	MEMRFNBR INT,
	AUDITCD VARCHAR(5),
	AUDITRESULT VARCHAR(5),
	AUDITREASON VARCHAR(300),
	AUDITREASONCD VARCHAR(2)
	)
	
	INSERT INTO @MEMBER_IRENT (MEMRFNBR,AUDITCD,AUDITRESULT,AUDITREASON,AUDITREASONCD)
	SELECT DISTINCT A.MEMRFNBR,A.AUDITCD,A.AUDITRESULT,A.AUDITREASON,A.AUDITREASONCD 
	FROM MEMBER_IRENT A WITH(NOLOCK) JOIN @MEMBER_IRENT_DISTINCT B ON A.MEMRFNBR=B.MEMRFNBR AND A.A_SYSDT=B.A_SYSDT
	WHERE A.AUDITCD='01'

	--SELECT COUNT(*) FROM @MEMBER_IRENT
	--TRUNCATE TABLE TB_MemberData_TransTest
	INSERT INTO TB_MemberData_TransTest
	(A_PRGID, A_USERID, A_SYSDT, U_PRGID, U_USERID, U_SYSDT, MEMIDNO, MEMCNAME, MEMPWD, 
	MEMTEL, MEMHTEL, MEMBIRTH, MEMCOUNTRY, MEMCITY, MEMADDR, MEMEMAIL, MEMCOMTEL, 
	MEMCONTRACT, MEMCONTEL, MEMMSG, CARDNO, UNIMNO, MEMSENDCD, CARRIERID, NPOBAN, HasVaildEMail, 
	HasCheckMobile, NeedChangePWD, HasBindSocial, Audit, AuditMessage, IrFlag, PayMode, RentType,
	MEMRFNBR,SIDENTITY
	)
	SELECT DISTINCT
		A_PRGID=0, 
		A.A_USERID, 
		A.A_SYSDT, 
		U_PRGID=0, 
		A.U_USERID, 
		A.U_SYSDT, 
		A.MEMIDNO, 
		MEMCNAME=LEFT(A.MEMCNAME,10),  --轉檔有被截斷的問題
		MEMPWD=sys.fn_varbintohexstr(HASHBYTES('SHA2_256',ISNULL(A.MEMPWD,''))),  --轉檔有NULL的問題
		MEMTEL=ISNULL(A.MEMCEIL,''), 
		MEMHTEL=A.MEMTEL, 
		MEMBIRTH=ISNULL(A.MEMBIRTH,''), 
		MEMCOUNTRY=ISNULL(A.MEMCOUNTRY,0),   --轉檔有NULL的問題
		MEMCITY=ISNULL(A.MEMCITY,0), 
		MEMADDR=ISNULL(A.MEMADDR,''), 
		MEMEMAIL=ISNULL(A.MEMEMAIL,''), 
		MEMCOMTEL=ISNULL(A.MEMCOMTEL,''),   --轉檔有NULL的問題 
		MEMCONTRACT=LEFT(ISNULL(A.MEMCONTRACT,''),10),  --轉檔有被截斷的問題
		MEMCONTEL=ISNULL(A.MEMCONTEL,''),   --轉檔有NULL的問題
		MEMMSG=ISNULL(A.MEMMSG,''), 
		CARDNO=A.CARDNO2,	--卡片內碼
		UNIMNO=ISNULL(A.MEMCOMNO,''),   --轉檔有NULL的問題
		MEMSENDCD=ISNULL(A.IRENTSENDCD,2),    --轉檔有NULL的問題，遇到NULL預設EMAIL
		CARRIERID=LEFT(ISNULL(C.CARRIERID,''),20), --轉檔有被截斷的問題
		NPOBAN=ISNULL(C.NPOBAN,''), 
		HasVaildEMail=0,	--是否有驗證email;0:否;1:是
		HasCheckMobile=CASE WHEN A.MEMGROUP='A' THEN 0 WHEN A.MEMGROUP='Y' THEN 1 ELSE 0 END,	--是否通過手機驗證(0:否;1:是)
		NeedChangePWD=0,	--是否需重新設定密碼(0:否;1:是)
		HasBindSocial=0,	--是否綁定社群(0:否;1:是)
		Audit=CASE WHEN A.IRENTFLG='Y' THEN 1 WHEN A.IRENTFLG='T' THEN 2 ELSE 0 END,		--是否通過審核(0:未審;1:已審;2:審核不通過)
		AuditMessage=RTRIM(ISNULL(E.MNAME1,''))+RTRIM(ISNULL(D.AUDITREASON,'')),	--審核不通過原因
		IrFlag=0,	--目前註冊進行至哪個步驟
		PayMode=0,	--付費方式：0:信用卡;1:和雲錢包;2:line pay;3:街口支付
		RentType=CASE WHEN A.IRENTFLG='N' OR A.MEMGROUP<>'Y' THEN 0		--可租車類別：0:無法;1:汽車;2:機車;3:全部
					WHEN A.IRENTFLG='Y' AND A.MEMGROUP='Y' AND A.MEMLICENCE01='Y' AND (A.MEMLICENCE02='Y' OR A.MEMLICENCE03='Y' OR A.MEMLICENCE04='Y') THEN 3
					WHEN A.IRENTFLG='Y' AND A.MEMGROUP='Y' AND A.MEMLICENCE01='Y' THEN 1
					WHEN A.IRENTFLG='Y' AND A.MEMGROUP='Y' AND (A.MEMLICENCE02='Y' OR A.MEMLICENCE03='Y' OR A.MEMLICENCE04='Y') THEN 2
					ELSE 0 END,
		A.MEMRFNBR,ISNULL(A.SIDENTITY,'')
	FROM MEMBER_NEW A WITH(NOLOCK)
	LEFT JOIN MEMBER_API B WITH(NOLOCK) ON B.MEMIDNO=A.MEMIDNO
	LEFT JOIN TB_MemberData F WITH(NOLOCK) ON A.MEMIDNO=F.MEMIDNO
	LEFT JOIN MEMBER_NEW_ONTRANS C WITH(NOLOCK) ON C.MEMIDNO=A.MEMIDNO
	LEFT JOIN @MEMBER_IRENT D ON D.MEMRFNBR=A.MEMRFNBR AND D.AUDITCD = '01'
	LEFT JOIN WEBCODEMF E WITH(NOLOCK) ON E.SYSCD='WEB' AND E.DATAID IN ('D1') AND D.AUDITREASONCD = E.MCODE
	WHERE F.MEMIDNO IS NULL
	AND A.IRENTFLG='Y'

	ROLLBACK TRAN

END
GO