--上線可以全開
TRUNCATE TABLE TB_Credentials
SELECT A.MEMIDNO AS CUSTID,A.IRENTFLG,A.MEMLICENCE01,A.MEMLICENCE02,A.MEMLICENCE03,A.MEMLICENCE04 
INTO #CUSTID
FROM MEMBER_NEW A WITH(NOLOCK)
JOIN MEMBER_API B WITH(NOLOCK) ON A.MEMIDNO=B.MEMIDNO

--SELECT * FROM LCCUSTAGREEDF WITH(NOLOCK) WHERE CUSTID='A122364317'
BEGIN TRAN
--delete from TB_Credentials where IDNO='A122364317'
INSERT INTO TB_Credentials (IDNO,ID_1,ID_2,CarDriver_1,CarDriver_2,MotorDriver_1,MotorDriver_2,Self_1,Law_Agent,Other_1,Signture,MKTime,UPDTime)
SELECT CUSTID
,ID_1 = CASE WHEN [02]<>'' AND IRENTFLG='Y' THEN 2 WHEN [02]<>'' AND IRENTFLG='T' THEN -1 WHEN [02]<>'' THEN 1 ELSE 0 END
,ID_2 = CASE WHEN [03]<>'' AND IRENTFLG='Y' THEN 2 WHEN [03]<>'' AND IRENTFLG='T' THEN -1 WHEN [03]<>'' THEN 1 ELSE 0 END
,CarDriver_1 = CASE WHEN MEMLICENCE01='Y' AND [04]<>'' AND IRENTFLG='Y' THEN 2 
					WHEN IRENTFLG='T' AND [04]<>'' THEN -1 
					WHEN IRENTFLG='S' AND [04]<>'' THEN 1 
					WHEN [04]<>'' THEN 1 ELSE 0 END
,CarDriver_2 =  CASE WHEN MEMLICENCE01='Y' AND [05]<>'' AND IRENTFLG='Y' THEN 2 
					WHEN IRENTFLG='T' AND [05]<>'' THEN -1 
					WHEN IRENTFLG='S' AND [05]<>'' THEN 1 
					WHEN [05]<>'' THEN 1 ELSE 0 END
,Other_1 = CASE WHEN [06]<>'' THEN 2 ELSE 0 END
,Self_1 = CASE WHEN [07]<>'' AND IRENTFLG='Y' THEN 2 WHEN [07]<>'' AND IRENTFLG='T' THEN -1 WHEN [07]<>'' THEN 1 ELSE 0 END
,MotorDriver_1 = CASE WHEN (MEMLICENCE02='Y' OR MEMLICENCE03='Y' OR MEMLICENCE04='Y') AND IRENTFLG='Y' THEN 2 WHEN [09]<>'' THEN 1 ELSE 0 END
,MotorDriver_2 = CASE WHEN (MEMLICENCE02='Y' OR MEMLICENCE03='Y' OR MEMLICENCE04='Y') AND IRENTFLG='Y' THEN 2 WHEN [10]<>'' THEN 1 ELSE 0 END
,Signture = CASE WHEN [SG]<>'' AND IRENTFLG='Y' THEN 2 WHEN [SG]<>'' THEN 1 ELSE 0 END
,Law_Agent = CASE WHEN [11]<>'' AND IRENTFLG='Y' THEN 2 WHEN [11]<>'' THEN 1 ELSE 0 END
,DATEADD(hour,8,GETDATE()) AS MKTime
,DATEADD(hour,8,GETDATE()) AS UPDTime
FROM (
	SELECT A.CUSTID, A.FILEITEM, A.FILEPATH,B.MEMLICENCE01,B.MEMLICENCE02,B.MEMLICENCE03,B.MEMLICENCE04,B.IRENTFLG
	FROM LCCUSTAGREEDF A WITH(NOLOCK)
	JOIN #CUSTID B WITH(NOLOCK) ON A.CUSTID=B.CUSTID
	LEFT JOIN TB_Credentials C WITH(NOLOCK) ON A.CUSTID=C.IDNO
	WHERE C.IDNO IS NULL
) T
PIVOT (
	MAX(FILEPATH)
	FOR FILEITEM IN ([02],[03],[04],[05],[06],[07],[09],[10],[SG],[11])
) P;

COMMIT TRAN

DROP TABLE #CUSTID