grpc-gen-user:
	@ protoc --go_out=. --go_opt=paths=source_relative `
    --go-grpc_out=. --go-grpc_opt=paths=source_relative `
    ./apiproto/user/user.proto

grpc-gen-user:
	@ protoc --go_out=. --go_opt=paths=source_relative `
    --go-grpc_out=. --go-grpc_opt=paths=source_relative `
    ./service/middleware/utils/middleware.proto