// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"example/n-tier-example/service/user"
)

// Injectors from wire.go:

func InitializeUserService() *user.UserService {
	userRepository := user.NewRepository()
	userService := user.NewService(userRepository)
	return userService
}
